version: '3'

services:
  burger-builder-postgres:
    image: postgres:9.6
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=burger-builder
      - POSTGRES_PASSWORD=burger-builder
      - POSTGRES_DB=burger-builder
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - local-environment-network

  burger-builder-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@burger-builder.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - burger-builder-postgres
    networks:
      - local-environment-network

  burger-builder-mailhog:
    restart: always
    image: mailhog/mailhog:latest
    logging:
      # Disable logs
      driver: 'none'
    ports:
      - 10251:1025
      - 8025:8025
    networks:
      - local-environment-network

networks:
  local-environment-network:
    driver: bridge
